services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: acc
      MYSQL_DATABASE: acc
      MYSQL_USER: acc
      MYSQL_PASSWORD: acc
    volumes:
      - db_data:/var/lib/mysql
networks:
  postgres:
    driver: bridge
volumes:
  db_data:
